name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  autoapprove:
    if: ${{ github.event.label.name == 'automerge' }}
    runs-on: ubuntu-latest
    steps:
      - id: autoapprove
        name: autoapprove
        uses: "juliangruber/approve-pull-request-action@v2.0.1"
        with:
            github-token: "${{ secrets.GITHUB_TOKEN }}"
            number: "${{ github.event.number }}"

  automerge:
    needs: [autoapprove]
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "aiqueneldar/automerge-action@add-blocked-status-as-mergeable"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          LOG: "DEBUG"
